# tomcat server port
server:
  port: 9080
  servlet:
    context-path: /api

#======================================
# data source connection configuration
#======================================
#spring.datasource.url=jdbc:mysql://NUC-W10P:63306/bookstore
#spring.datasource.driver-class-name=org.h2.Driver
spring:
  datasource:
    url: jdbc:sqlserver://NUC-W10P;databaseName=movielibrary
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: alex
    password: Pa$$w0rd
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

